apiVersion: v1
kind: Pod
metadata:
  name: dbstack
spec:
  containers:
    - name: mysql
      image: docker.io/mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mi_contraseña_segura"
      ports:
        - containerPort: 3306
          hostPort: 3306
      volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
    - name: mysql-workbench
      image: lscr.io/linuxserver/mysql-workbench
      ports:
        - containerPort: 3000
          hostPort: 3000
  volumes:
    - name: mysql-data
      persistentVolumeClaim:
        claimName: mysql-data-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
